// Where this kiosk physically stands, as a Node. Hard-coded until the admin
// CMS can assign a location per kiosk (see the "Kiosk identity" proposal in
// the hand-off notes); when that lands, only findKioskNode's source of the
// descriptor changes, not its callers.
//
// Matched by building + floor + name rather than a node id, because ids are
// generated by the backend and differ per deployment.
export const KIOSK_LOCATION = { building: "gd3", floor: 4, nameIncludes: "inner wing" };

export function findKioskNode(nodes, location = KIOSK_LOCATION) {
  if (!nodes) return null;
  return (
    nodes.find(
      (n) =>
        n.building === location.building &&
        Number(n.floor) === location.floor &&
        n.name?.toLowerCase().includes(location.nameIncludes)
    ) || null
  );
}
